"""empty message

Revision ID: acd9c55de271
Revises: 71d1f7bf721c
Create Date: 2018-12-13 06:02:25.874777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acd9c55de271'
down_revision = '71d1f7bf721c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.create_table('testing',
    sa.Column('ID', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('lastModifiedDate', sa.DateTime(), nullable=False),
    sa.Column('restId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('restId')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_table('testing')

    # ### end Alembic commands ###
